apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: operator
    meta.helm.sh/release-namespace: minio-operator
  creationTimestamp: "2024-02-24T10:10:41Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: v5.0.12
    helm.sh/chart: operator-5.0.12
  name: console
  namespace: minio-operator
  resourceVersion: "285099"
  uid: 047d29ee-b8ce-43cd-a070-a6a2b29823a3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: operator-console
      app.kubernetes.io/name: operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: operator-console
        app.kubernetes.io/name: operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - minio-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - ui
        - --certs-dir=/tmp/certs
        image: quay.io/minio/operator:v5.0.12
        imagePullPolicy: IfNotPresent
        name: operator
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 9443
          name: https
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/certs/CAs
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: console-sa
      serviceAccountName: console-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-24T10:10:41Z"
    lastUpdateTime: "2024-02-24T10:10:45Z"
    message: ReplicaSet "console-55c68f95f6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-02-27T19:43:52Z"
    lastUpdateTime: "2024-02-27T19:43:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
